// Mocks generated by Mockito 5.4.6 from annotations
// in nyarios/test/ui/home/recent_chat/recent_chat_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:nyarios/data/repositories/chat_repository.dart' as _i4;
import 'package:nyarios/data/sources/local/shared_local_source.dart' as _i2;
import 'package:nyarios/data/sources/remote/chat_remote_source.dart' as _i3;
import 'package:nyarios/domain/model/chat.dart' as _i6;
import 'package:nyarios/domain/model/message.dart' as _i8;
import 'package:nyarios/domain/model/recent_chat.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedLocalSource_0 extends _i1.SmartFake
    implements _i2.SharedLocalSource {
  _FakeSharedLocalSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatRemoteSource_1 extends _i1.SmartFake
    implements _i3.ChatRemoteSource {
  _FakeChatRemoteSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i4.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i3.ChatRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeChatRemoteSource_1(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i3.ChatRemoteSource);

  @override
  _i5.Future<String> createChatRoom(
    _i6.Chat? chat,
    String? receiverProfileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createChatRoom, [chat, receiverProfileId]),
            returnValue: _i5.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#createChatRoom, [chat, receiverProfileId]),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<void> sendMessage(
    String? chatId,
    String? type,
    String? text,
    String? replyTo,
    String? receiverProfileId,
    String? fileSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [
              chatId,
              type,
              text,
              replyTo,
              receiverProfileId,
              fileSize,
            ]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i8.Message>> streamChatMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#streamChatMessages, [chatId]),
            returnValue: _i5.Stream<List<_i8.Message>>.empty(),
          )
          as _i5.Stream<List<_i8.Message>>);

  @override
  _i5.Future<void> deleteMessages(
    String? chatId,
    List<_i8.Message>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessages, [chatId, messages]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i8.Message>> loadMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#loadMessages, [chatId]),
            returnValue: _i5.Future<List<_i8.Message>>.value(<_i8.Message>[]),
          )
          as _i5.Future<List<_i8.Message>>);

  @override
  _i5.Future<List<_i9.RecentChat>> loadRecentChats() =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentChats, []),
            returnValue: _i5.Future<List<_i9.RecentChat>>.value(
              <_i9.RecentChat>[],
            ),
          )
          as _i5.Future<List<_i9.RecentChat>>);

  @override
  _i5.Stream<List<_i9.RecentChat>> streamRecentChats() =>
      (super.noSuchMethod(
            Invocation.method(#streamRecentChats, []),
            returnValue: _i5.Stream<List<_i9.RecentChat>>.empty(),
          )
          as _i5.Stream<List<_i9.RecentChat>>);
}
