// Mocks generated by Mockito 5.4.6 from annotations
// in nyarios/test/ui/auth/signin_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:firebase_messaging/firebase_messaging.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:nyarios/data/repositories/profile_repository.dart' as _i6;
import 'package:nyarios/data/sources/local/shared_local_source.dart' as _i2;
import 'package:nyarios/data/sources/remote/profile_remote_source.dart' as _i3;
import 'package:nyarios/domain/model/profile.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedLocalSource_0 extends _i1.SmartFake
    implements _i2.SharedLocalSource {
  _FakeSharedLocalSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileRemoteSource_1 extends _i1.SmartFake
    implements _i3.ProfileRemoteSource {
  _FakeProfileRemoteSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseMessaging_2 extends _i1.SmartFake
    implements _i4.FirebaseMessaging {
  _FakeFirebaseMessaging_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_3 extends _i1.SmartFake implements _i5.Profile {
  _FakeProfile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i6.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i3.ProfileRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeProfileRemoteSource_1(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i3.ProfileRemoteSource);

  @override
  _i4.FirebaseMessaging get firebaseMessaging =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseMessaging),
            returnValue: _FakeFirebaseMessaging_2(
              this,
              Invocation.getter(#firebaseMessaging),
            ),
          )
          as _i4.FirebaseMessaging);

  @override
  _i7.Future<bool> signInUser({
    required String? accessToken,
    required String? idToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInUser, [], {
              #accessToken: accessToken,
              #idToken: idToken,
            }),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<_i5.Profile> loadSingleProfile(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSingleProfile, [profileId]),
            returnValue: _i7.Future<_i5.Profile>.value(
              _FakeProfile_3(
                this,
                Invocation.method(#loadSingleProfile, [profileId]),
              ),
            ),
          )
          as _i7.Future<_i5.Profile>);

  @override
  _i7.Stream<bool> getOnlineStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineStatus, [userId]),
            returnValue: _i7.Stream<bool>.empty(),
          )
          as _i7.Stream<bool>);

  @override
  _i7.Stream<_i5.Profile> loadStreamProfile() =>
      (super.noSuchMethod(
            Invocation.method(#loadStreamProfile, []),
            returnValue: _i7.Stream<_i5.Profile>.empty(),
          )
          as _i7.Stream<_i5.Profile>);

  @override
  _i7.Future<void> setOnlineStatus(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setOnlineStatus, [status]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updateProfile(String? value, bool? updateName) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [value, updateName]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}
