const Map<String, String> idID = {
  "add_status": "Tambah Status",
  "view_contact": "Lihat Kontak",
  "settings": "Pengaturan",
  "common": "Umum",
  "other": "Lainnya",
  "dark_mode": "Mode Gelap",
  "language": "Bahasa",
  "rating": "Rating",
  "share": "Bagikan",
  "message": "Pesan",
  "yesterday": "Kemarin",
  "you": "Kamu",
  "empty_contact": "Kontak tidak ditemukan",
  "empty_chat": "Chat tidak ditemukan",
  "empty_media": "Media Kosong",
  "selected_chat": "chat terpilih",
  "search": "Cari",
  "something_wrong": "Terjadi kesalahan",
  "loading": "Memuat",
  "today": "Hari Ini",
  "messages_copied": "Pesan Disalin",
  "file": "Berkas",
  "gallery": "Galeri",
  "profile": "Profil",
  "search_contact": "Cari Kontak",
  "search_chat": "Cari Obrolan",
  "splash_message": "Nyarios",
  "start_conversation": "Mulai Pembicaraan",
  "media": "Media",
  "docs": "Dokumen",
  "name": "Nama",
  "logout": "Keluar",
  "block": "Blokir",
  "unblock": "Buka Blokir",
  "user_blocked": "Pengguna Diblokir",
  "add_friend": "Tambah Teman",
  "privacy": "Privasi",
  "contact": "Kontak",
  "no_friend": "Kamu Belum Memiliki Teman",
  "qr_code": "Kode QR",
  "blocked_friend": "Teman Diblokir",
  "empty_blocked_friend": "Belum Ada Teman Yang Diblokir",
  "copy_link": "Salin Tautan",
  "save": "Simpan",
  "scan_qr_code": "Pindai Kode QR",
  "scan_qr_message":
      "Gunakan kode QR atau tautan\nuntuk berteman dengan akun lain",
  "copy_clipboard": "Disalin ke Clipboard",
  "share_qr_code": "Bagikan Kode QR",
  "cancel": "Batal",
  "enter_name": "Masukkan nama anda",
  "enter_status": "Masukkan status anda",
  "fill_message": "Silahkan masukkan data anda",
  "create_group": "Buat Group",
  "group_name": "Nama Group Anda",
  "add_member": "Tambah Anggota",
  "member": "Anggota",
  "pick_member": "Pilih Anggota",
  "leave_group": "Tinggalkan Group",
  "leave_group_message": "Percakapan group anda akan terhapus, anda yakin?",
  "members": "Anggota",
  "edit_group": "Sunting Group",
  "enter_group_name": "Masukkan group anda",
};

const Map<String, String> enUS = {
  "add_status": "Add Status",
  "view_contact": "View Contact",
  "settings": "Settings",
  "common": "Comon",
  "other": "Other",
  "dark_mode": "Dark Mode",
  "language": "Language",
  "rating": "Rating",
  "share": "Share",
  "message": "Message",
  "yesterday": "Yesterday",
  "you": "you",
  "empty_contact": "There are no contact",
  "empty_chat": "There are no chat",
  "empty_media": "Media is Empty",
  "selected_chat": "chats selected",
  "search": "Search",
  "something_wrong": "Something went wrong",
  "loading": "Loading",
  "today": "Today",
  "messages_copied": "Messages Copied",
  "file": "File",
  "gallery": "Gallery",
  "profile": "Profile",
  "search_contact": "Search Contact",
  "search_chat": "Search Chat",
  "splash_message": "Nyarios",
  "start_conversation": "Start Conversation",
  "media": "Media",
  "docs": "Docs",
  "name": "Name",
  "logout": "Logout",
  "block": "Block",
  "unblock": "Unblock",
  "user_blocked": "User is Blocked",
  "add_friend": "Add Friend",
  "privacy": "Privacy",
  "contact": "Contact",
  "no_friend": "You Have No Friend",
  "qr_code": "QR Code",
  "blocked_friend": "Blocked Friend",
  "empty_blocked_friend": "There are no Blocked Friend",
  "copy_link": "Copy Link",
  "save": "Save",
  "scan_qr_code": "Scan QR Code",
  "scan_qr_message":
      "Show or send this QR code to\nfriends to let them add you",
  "copy_clipboard": "Copied to Clipboard",
  "share_qr_code": "Share QR Code",
  "cancel": "Cancel",
  "enter_name": "Enter your name",
  "enter_status": "Enter your status",
  "fill_message": "Please fill your data",
  "create_group": "Create Group",
  "group_name": "Your Group Name",
  "add_member": "Add Member",
  "member": "Member",
  "pick_member": "Pick Member",
  "leave_group": "Leave Group",
  "leave_group_message": "Your chat history will be deleted, are you sure?",
  "members": "Members",
  "edit_group": "Edit Group",
  "enter_group_name": "Enter group name",
};
