const Map<String, String> idID = {
  "add_status": "Tambah Status",
  "view_contact": "Lihat Kontak",
  "settings": "Pengaturan",
  "common": "Umum",
  "other": "Lainnya",
  "dark_mode": "Mode Gelap",
  "language": "Bahasa",
  "rating": "Rating",
  "share": "Bagikan",
  "message": "Pesan",
  "yesterday": "Kemarin",
  "you": "Kamu",
  "empty_contact": "Kontak tidak ditemukan",
  "empty_chat": "Chat tidak ditemukan",
  "empty_media": "Media Kosong",
  "selected_chat": "chat terpilih",
  "search": "Cari",
  "something_wrong": "Terjadi kesalahan",
  "loading": "Memuat",
  "today": "Hari Ini",
  "messages_copied": "Pesan Disalin",
  "file": "Berkas",
  "gallery": "Galeri",
  "profile": "Profil",
  "search_contact": "Cari Kontak",
  "search_chat": "Cari Obrolan",
  "splash_message": "Nyarios",
  "start_conversation": "Mulai Pembicaraan",
  "media": "Media",
  "docs": "Dokumen",
  "name": "Nama",
  "logout": "Keluar",
};

const Map<String, String> enUS = {
  "add_status": "Add Status",
  "view_contact": "View Contact",
  "settings": "Settings",
  "common": "Comon",
  "other": "Other",
  "dark_mode": "Dark Mode",
  "language": "Language",
  "rating": "Rating",
  "share": "Share",
  "message": "Message",
  "yesterday": "Yesterday",
  "you": "you",
  "empty_contact": "There are no contact",
  "empty_chat": "There are no chat",
  "empty_media": "Media is Empty",
  "selected_chat": "chats selected",
  "search": "Search",
  "something_wrong": "Something went wrong",
  "loading": "Loading",
  "today": "Today",
  "messages_copied": "Messages Copied",
  "file": "File",
  "gallery": "Gallery",
  "profile": "Profile",
  "search_contact": "Search Contact",
  "search_chat": "Search Chat",
  "splash_message": "Nyarios",
  "start_conversation": "Start Conversation",
  "media": "Media",
  "docs": "Docs",
  "name": "Name",
  "logout": "Logout",
};
