// Mocks generated by Mockito 5.4.6 from annotations
// in nyarios/test/data/repositories/chat_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:cloud_firestore/cloud_firestore.dart' as _i5;
import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:nyarios/core/services/shared_prefs_service.dart' as _i2;
import 'package:nyarios/data/sources/local/shared_local_source.dart' as _i6;
import 'package:nyarios/data/sources/remote/chat_remote_source.dart' as _i10;
import 'package:nyarios/data/sources/remote/post/chat_room_post.dart' as _i11;
import 'package:nyarios/data/sources/remote/post/message_post.dart' as _i12;
import 'package:nyarios/domain/model/local_user.dart' as _i3;
import 'package:nyarios/domain/model/message.dart' as _i13;
import 'package:nyarios/domain/model/profile.dart' as _i9;
import 'package:nyarios/domain/model/recent_chat.dart' as _i14;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPrefsService_0 extends _i1.SmartFake
    implements _i2.SharedPrefsService {
  _FakeSharedPrefsService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalUser_1 extends _i1.SmartFake implements _i3.LocalUser {
  _FakeLocalUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_2 extends _i1.SmartFake implements _i4.Dio {
  _FakeDio_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFirestore_3 extends _i1.SmartFake
    implements _i5.FirebaseFirestore {
  _FakeFirebaseFirestore_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedLocalSource extends _i1.Mock implements _i6.SharedLocalSource {
  MockSharedLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPrefsService get sharedPrefs =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPrefs),
            returnValue: _FakeSharedPrefsService_0(
              this,
              Invocation.getter(#sharedPrefs),
            ),
          )
          as _i2.SharedPrefsService);

  @override
  _i7.Future<void> setDarkMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDarkMode, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isDarkMode() =>
      (super.noSuchMethod(
            Invocation.method(#isDarkMode, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setAlreadyLogin(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAlreadyLogin, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isAlreadyLogin() =>
      (super.noSuchMethod(
            Invocation.method(#isAlreadyLogin, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setLanguage(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> gelectedLanguage() =>
      (super.noSuchMethod(
            Invocation.method(#gelectedLanguage, []),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#gelectedLanguage, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> setUserLocal(_i9.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#setUserLocal, [profile]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.LocalUser> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i7.Future<_i3.LocalUser>.value(
              _FakeLocalUser_1(this, Invocation.method(#getUserProfile, [])),
            ),
          )
          as _i7.Future<_i3.LocalUser>);
}

/// A class which mocks [ChatRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRemoteSource extends _i1.Mock implements _i10.ChatRemoteSource {
  MockChatRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_2(this, Invocation.getter(#dio)),
          )
          as _i4.Dio);

  @override
  _i5.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_3(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i5.FirebaseFirestore);

  @override
  _i7.Future<String> createChatRoom(_i11.ChatRoomPost? chat) =>
      (super.noSuchMethod(
            Invocation.method(#createChatRoom, [chat]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#createChatRoom, [chat]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<bool> sendMessage(_i12.MessagePost? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<List<_i13.Message>> getMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessages, [chatId]),
            returnValue: _i7.Future<List<_i13.Message>>.value(<_i13.Message>[]),
          )
          as _i7.Future<List<_i13.Message>>);

  @override
  _i7.Future<List<_i14.RecentChat>> getRecentChats(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#getRecentChats, [profileId]),
            returnValue: _i7.Future<List<_i14.RecentChat>>.value(
              <_i14.RecentChat>[],
            ),
          )
          as _i7.Future<List<_i14.RecentChat>>);

  @override
  _i7.Stream<List<_i13.Message>> streamMessages(String? roomId) =>
      (super.noSuchMethod(
            Invocation.method(#streamMessages, [roomId]),
            returnValue: _i7.Stream<List<_i13.Message>>.empty(),
          )
          as _i7.Stream<List<_i13.Message>>);

  @override
  _i7.Future<void> messagesBatchDelete(
    String? roomId,
    List<_i13.Message>? chatMessages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#messagesBatchDelete, [roomId, chatMessages]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Stream<List<_i14.RecentChat>> streamRecentChats(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#streamRecentChats, [userId]),
            returnValue: _i7.Stream<List<_i14.RecentChat>>.empty(),
          )
          as _i7.Stream<List<_i14.RecentChat>>);
}
