// Mocks generated by Mockito 5.4.6 from annotations
// in nyarios/test/data/repositories/contact_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:nyarios/core/services/shared_prefs_service.dart' as _i2;
import 'package:nyarios/data/sources/local/shared_local_source.dart' as _i6;
import 'package:nyarios/data/sources/remote/contact_remote_source.dart' as _i10;
import 'package:nyarios/domain/model/contact.dart' as _i5;
import 'package:nyarios/domain/model/local_user.dart' as _i3;
import 'package:nyarios/domain/model/profile.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedPrefsService_0 extends _i1.SmartFake
    implements _i2.SharedPrefsService {
  _FakeSharedPrefsService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalUser_1 extends _i1.SmartFake implements _i3.LocalUser {
  _FakeLocalUser_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_2 extends _i1.SmartFake implements _i4.Dio {
  _FakeDio_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContact_3 extends _i1.SmartFake implements _i5.Contact {
  _FakeContact_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SharedLocalSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedLocalSource extends _i1.Mock implements _i6.SharedLocalSource {
  MockSharedLocalSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedPrefsService get sharedPrefs =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPrefs),
            returnValue: _FakeSharedPrefsService_0(
              this,
              Invocation.getter(#sharedPrefs),
            ),
          )
          as _i2.SharedPrefsService);

  @override
  _i7.Future<void> setDarkMode(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setDarkMode, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isDarkMode() =>
      (super.noSuchMethod(
            Invocation.method(#isDarkMode, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setAlreadyLogin(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAlreadyLogin, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<bool> isAlreadyLogin() =>
      (super.noSuchMethod(
            Invocation.method(#isAlreadyLogin, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<void> setLanguage(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [value]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<String> gelectedLanguage() =>
      (super.noSuchMethod(
            Invocation.method(#gelectedLanguage, []),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#gelectedLanguage, []),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<void> setUserLocal(_i9.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#setUserLocal, [profile]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.LocalUser> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i7.Future<_i3.LocalUser>.value(
              _FakeLocalUser_1(this, Invocation.method(#getUserProfile, [])),
            ),
          )
          as _i7.Future<_i3.LocalUser>);
}

/// A class which mocks [ContactRemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRemoteSource extends _i1.Mock
    implements _i10.ContactRemoteSource {
  MockContactRemoteSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_2(this, Invocation.getter(#dio)),
          )
          as _i4.Dio);

  @override
  _i7.Future<List<_i9.Profile>> getContactByStatus(
    String? profileId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactByStatus, [profileId, status]),
            returnValue: _i7.Future<List<_i9.Profile>>.value(<_i9.Profile>[]),
          )
          as _i7.Future<List<_i9.Profile>>);

  @override
  _i7.Future<_i5.Contact> getContactDetail(
    String? ownerProfileId,
    String? contactProfileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getContactDetail, [
              ownerProfileId,
              contactProfileId,
            ]),
            returnValue: _i7.Future<_i5.Contact>.value(
              _FakeContact_3(
                this,
                Invocation.method(#getContactDetail, [
                  ownerProfileId,
                  contactProfileId,
                ]),
              ),
            ),
          )
          as _i7.Future<_i5.Contact>);

  @override
  _i7.Future<bool> updateContactStatus(
    String? ownerProfileId,
    String? contactProfileId,
    String? status,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateContactStatus, [
              ownerProfileId,
              contactProfileId,
              status,
            ]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);
}
