// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeIOjIVr0jRnon2Cz6igoP7K7E4-lJoAM',
    appId: '1:903393083090:android:96eae22fd960a86947b70b',
    messagingSenderId: '903393083090',
    projectId: 'nyarios-b45ca',
    storageBucket: 'nyarios-b45ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYlTcsUH7MsrKa2xUTCfKb-HX9JAyQqUY',
    appId: '1:903393083090:ios:2256c8e388c3e81147b70b',
    messagingSenderId: '903393083090',
    projectId: 'nyarios-b45ca',
    storageBucket: 'nyarios-b45ca.appspot.com',
    androidClientId: '903393083090-o8reqebkbrsd38lkl8cv775h9l1cv5uv.apps.googleusercontent.com',
    iosClientId: '903393083090-kjmqbo88fuj9a3eni69lg3n0rodduika.apps.googleusercontent.com',
    iosBundleId: 'com.app.zuludin.nyarios',
  );
}
