// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB8iAe3lYmAKm7_rJHs1eajassIjlrkik',
    appId: '1:550134906790:android:abb295f13a89375f261967',
    messagingSenderId: '550134906790',
    projectId: 'nyarios-364708',
    storageBucket: 'nyarios-364708.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHmNTBL-tQ_5SeHcFX_9yDZ0fHH1mFmWA',
    appId: '1:550134906790:ios:75023864a5798c48261967',
    messagingSenderId: '550134906790',
    projectId: 'nyarios-364708',
    storageBucket: 'nyarios-364708.appspot.com',
    androidClientId: '550134906790-bh2cbat36i7r8b3uif0vi3q9rjs2knq9.apps.googleusercontent.com',
    iosClientId: '550134906790-20rof4tj6shslblah1p2k0sci827v4mc.apps.googleusercontent.com',
    iosBundleId: 'com.app.zuludin.nyarios',
  );

}