// Mocks generated by Mockito 5.4.6 from annotations
// in nyarios/test/ui/chat/chatting_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:nyarios/core/services/shared_prefs_service.dart' as _i5;
import 'package:nyarios/data/repositories/call_repository.dart' as _i18;
import 'package:nyarios/data/repositories/chat_repository.dart' as _i8;
import 'package:nyarios/data/repositories/contact_repository.dart' as _i14;
import 'package:nyarios/data/repositories/shared_local_repository.dart' as _i17;
import 'package:nyarios/data/sources/local/shared_local_source.dart' as _i2;
import 'package:nyarios/data/sources/remote/call_remote_source.dart' as _i7;
import 'package:nyarios/data/sources/remote/chat_remote_source.dart' as _i3;
import 'package:nyarios/data/sources/remote/contact_remote_source.dart' as _i4;
import 'package:nyarios/domain/model/call.dart' as _i19;
import 'package:nyarios/domain/model/chat.dart' as _i10;
import 'package:nyarios/domain/model/contact.dart' as _i16;
import 'package:nyarios/domain/model/local_user.dart' as _i6;
import 'package:nyarios/domain/model/message.dart' as _i12;
import 'package:nyarios/domain/model/profile.dart' as _i15;
import 'package:nyarios/domain/model/recent_chat.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedLocalSource_0 extends _i1.SmartFake
    implements _i2.SharedLocalSource {
  _FakeSharedLocalSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatRemoteSource_1 extends _i1.SmartFake
    implements _i3.ChatRemoteSource {
  _FakeChatRemoteSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContactRemoteSource_2 extends _i1.SmartFake
    implements _i4.ContactRemoteSource {
  _FakeContactRemoteSource_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSharedPrefsService_3 extends _i1.SmartFake
    implements _i5.SharedPrefsService {
  _FakeSharedPrefsService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocalUser_4 extends _i1.SmartFake implements _i6.LocalUser {
  _FakeLocalUser_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCallRemoteSource_5 extends _i1.SmartFake
    implements _i7.CallRemoteSource {
  _FakeCallRemoteSource_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i8.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i3.ChatRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeChatRemoteSource_1(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i3.ChatRemoteSource);

  @override
  _i9.Future<String> createChatRoom(
    _i10.Chat? chat,
    String? receiverProfileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createChatRoom, [chat, receiverProfileId]),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createChatRoom, [chat, receiverProfileId]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> sendMessage(
    String? chatId,
    String? type,
    String? text,
    String? replyTo,
    String? receiverProfileId,
    String? fileSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [
              chatId,
              type,
              text,
              replyTo,
              receiverProfileId,
              fileSize,
            ]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<List<_i12.Message>> streamChatMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#streamChatMessages, [chatId]),
            returnValue: _i9.Stream<List<_i12.Message>>.empty(),
          )
          as _i9.Stream<List<_i12.Message>>);

  @override
  _i9.Future<void> deleteMessages(
    String? chatId,
    List<_i12.Message>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessages, [chatId, messages]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<List<_i12.Message>> loadMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#loadMessages, [chatId]),
            returnValue: _i9.Future<List<_i12.Message>>.value(<_i12.Message>[]),
          )
          as _i9.Future<List<_i12.Message>>);

  @override
  _i9.Future<List<_i13.RecentChat>> loadRecentChats() =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentChats, []),
            returnValue: _i9.Future<List<_i13.RecentChat>>.value(
              <_i13.RecentChat>[],
            ),
          )
          as _i9.Future<List<_i13.RecentChat>>);

  @override
  _i9.Stream<List<_i13.RecentChat>> streamRecentChats() =>
      (super.noSuchMethod(
            Invocation.method(#streamRecentChats, []),
            returnValue: _i9.Stream<List<_i13.RecentChat>>.empty(),
          )
          as _i9.Stream<List<_i13.RecentChat>>);
}

/// A class which mocks [ContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRepository extends _i1.Mock implements _i14.ContactRepository {
  MockContactRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i4.ContactRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeContactRemoteSource_2(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i4.ContactRemoteSource);

  @override
  _i9.Future<List<_i15.Profile>> loadContacts(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#loadContacts, [status]),
            returnValue: _i9.Future<List<_i15.Profile>>.value(<_i15.Profile>[]),
          )
          as _i9.Future<List<_i15.Profile>>);

  @override
  _i9.Future<void> changeContactStatus(String? otherUserId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#changeContactStatus, [otherUserId, status]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i16.Contact?> loadSingleContact(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSingleContact, [profileId]),
            returnValue: _i9.Future<_i16.Contact?>.value(),
          )
          as _i9.Future<_i16.Contact?>);
}

/// A class which mocks [SharedLocalRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSharedLocalRepository extends _i1.Mock
    implements _i17.SharedLocalRepository {
  MockSharedLocalRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.SharedPrefsService get sharedPrefs =>
      (super.noSuchMethod(
            Invocation.getter(#sharedPrefs),
            returnValue: _FakeSharedPrefsService_3(
              this,
              Invocation.getter(#sharedPrefs),
            ),
          )
          as _i5.SharedPrefsService);

  @override
  _i9.Future<void> setAppTheme(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAppTheme, [value]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> getAppTheme() =>
      (super.noSuchMethod(
            Invocation.method(#getAppTheme, []),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#getAppTheme, []),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> setAlreadyLogin(bool? value) =>
      (super.noSuchMethod(
            Invocation.method(#setAlreadyLogin, [value]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<bool> isAlreadyLogin() =>
      (super.noSuchMethod(
            Invocation.method(#isAlreadyLogin, []),
            returnValue: _i9.Future<bool>.value(false),
          )
          as _i9.Future<bool>);

  @override
  _i9.Future<void> setLanguage(String? value) =>
      (super.noSuchMethod(
            Invocation.method(#setLanguage, [value]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<String> gelectedLanguage() =>
      (super.noSuchMethod(
            Invocation.method(#gelectedLanguage, []),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#gelectedLanguage, []),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> setUserLocal(_i15.Profile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#setUserLocal, [profile]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Future<_i6.LocalUser> getUserProfile() =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, []),
            returnValue: _i9.Future<_i6.LocalUser>.value(
              _FakeLocalUser_4(this, Invocation.method(#getUserProfile, [])),
            ),
          )
          as _i9.Future<_i6.LocalUser>);
}

/// A class which mocks [CallRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCallRepository extends _i1.Mock implements _i18.CallRepository {
  MockCallRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i7.CallRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeCallRemoteSource_5(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i7.CallRemoteSource);

  @override
  _i9.Future<String> createCall(
    String? type,
    String? receiverProfileId,
    String? chatId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createCall, [type, receiverProfileId, chatId]),
            returnValue: _i9.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createCall, [
                  type,
                  receiverProfileId,
                  chatId,
                ]),
              ),
            ),
          )
          as _i9.Future<String>);

  @override
  _i9.Future<void> updateCallStatus(String? callId, String? callerProfileId) =>
      (super.noSuchMethod(
            Invocation.method(#updateCallStatus, [callId, callerProfileId]),
            returnValue: _i9.Future<void>.value(),
            returnValueForMissingStub: _i9.Future<void>.value(),
          )
          as _i9.Future<void>);

  @override
  _i9.Stream<List<_i19.Call>> streamCallHistories() =>
      (super.noSuchMethod(
            Invocation.method(#streamCallHistories, []),
            returnValue: _i9.Stream<List<_i19.Call>>.empty(),
          )
          as _i9.Stream<List<_i19.Call>>);
}
