// Mocks generated by Mockito 5.4.6 from annotations
// in nyarios/test/ui/contact/contact_detail_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:firebase_messaging/firebase_messaging.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i11;
import 'package:nyarios/data/repositories/chat_repository.dart' as _i9;
import 'package:nyarios/data/repositories/profile_repository.dart' as _i7;
import 'package:nyarios/data/sources/local/shared_local_source.dart' as _i2;
import 'package:nyarios/data/sources/remote/chat_remote_source.dart' as _i6;
import 'package:nyarios/data/sources/remote/profile_remote_source.dart' as _i3;
import 'package:nyarios/domain/model/chat.dart' as _i10;
import 'package:nyarios/domain/model/message.dart' as _i12;
import 'package:nyarios/domain/model/profile.dart' as _i5;
import 'package:nyarios/domain/model/recent_chat.dart' as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedLocalSource_0 extends _i1.SmartFake
    implements _i2.SharedLocalSource {
  _FakeSharedLocalSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfileRemoteSource_1 extends _i1.SmartFake
    implements _i3.ProfileRemoteSource {
  _FakeProfileRemoteSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseMessaging_2 extends _i1.SmartFake
    implements _i4.FirebaseMessaging {
  _FakeFirebaseMessaging_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProfile_3 extends _i1.SmartFake implements _i5.Profile {
  _FakeProfile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatRemoteSource_4 extends _i1.SmartFake
    implements _i6.ChatRemoteSource {
  _FakeChatRemoteSource_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i7.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i3.ProfileRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeProfileRemoteSource_1(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i3.ProfileRemoteSource);

  @override
  _i4.FirebaseMessaging get firebaseMessaging =>
      (super.noSuchMethod(
            Invocation.getter(#firebaseMessaging),
            returnValue: _FakeFirebaseMessaging_2(
              this,
              Invocation.getter(#firebaseMessaging),
            ),
          )
          as _i4.FirebaseMessaging);

  @override
  _i8.Future<bool> signInUser({
    required String? accessToken,
    required String? idToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signInUser, [], {
              #accessToken: accessToken,
              #idToken: idToken,
            }),
            returnValue: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i5.Profile> loadSingleProfile(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSingleProfile, [profileId]),
            returnValue: _i8.Future<_i5.Profile>.value(
              _FakeProfile_3(
                this,
                Invocation.method(#loadSingleProfile, [profileId]),
              ),
            ),
          )
          as _i8.Future<_i5.Profile>);

  @override
  _i8.Stream<bool> getOnlineStatus(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getOnlineStatus, [userId]),
            returnValue: _i8.Stream<bool>.empty(),
          )
          as _i8.Stream<bool>);

  @override
  _i8.Stream<_i5.Profile> loadStreamProfile() =>
      (super.noSuchMethod(
            Invocation.method(#loadStreamProfile, []),
            returnValue: _i8.Stream<_i5.Profile>.empty(),
          )
          as _i8.Stream<_i5.Profile>);

  @override
  _i8.Future<void> setOnlineStatus(bool? status) =>
      (super.noSuchMethod(
            Invocation.method(#setOnlineStatus, [status]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateProfile(String? value, bool? updateName) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [value, updateName]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [ChatRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepository extends _i1.Mock implements _i9.ChatRepository {
  MockChatRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i6.ChatRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeChatRemoteSource_4(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i6.ChatRemoteSource);

  @override
  _i8.Future<String> createChatRoom(
    _i10.Chat? chat,
    String? receiverProfileId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createChatRoom, [chat, receiverProfileId]),
            returnValue: _i8.Future<String>.value(
              _i11.dummyValue<String>(
                this,
                Invocation.method(#createChatRoom, [chat, receiverProfileId]),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  _i8.Future<void> sendMessage(
    String? chatId,
    String? type,
    String? text,
    String? replyTo,
    String? receiverProfileId,
    String? fileSize,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [
              chatId,
              type,
              text,
              replyTo,
              receiverProfileId,
              fileSize,
            ]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i12.Message>> streamChatMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#streamChatMessages, [chatId]),
            returnValue: _i8.Stream<List<_i12.Message>>.empty(),
          )
          as _i8.Stream<List<_i12.Message>>);

  @override
  _i8.Future<void> deleteMessages(
    String? chatId,
    List<_i12.Message>? messages,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessages, [chatId, messages]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<List<_i12.Message>> loadMessages(String? chatId) =>
      (super.noSuchMethod(
            Invocation.method(#loadMessages, [chatId]),
            returnValue: _i8.Future<List<_i12.Message>>.value(<_i12.Message>[]),
          )
          as _i8.Future<List<_i12.Message>>);

  @override
  _i8.Future<List<_i13.RecentChat>> loadRecentChats() =>
      (super.noSuchMethod(
            Invocation.method(#loadRecentChats, []),
            returnValue: _i8.Future<List<_i13.RecentChat>>.value(
              <_i13.RecentChat>[],
            ),
          )
          as _i8.Future<List<_i13.RecentChat>>);

  @override
  _i8.Stream<List<_i13.RecentChat>> streamRecentChats() =>
      (super.noSuchMethod(
            Invocation.method(#streamRecentChats, []),
            returnValue: _i8.Stream<List<_i13.RecentChat>>.empty(),
          )
          as _i8.Stream<List<_i13.RecentChat>>);
}
