// Mocks generated by Mockito 5.4.6 from annotations
// in nyarios/test/ui/friend/friend_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:nyarios/data/repositories/contact_repository.dart' as _i4;
import 'package:nyarios/data/sources/local/shared_local_source.dart' as _i2;
import 'package:nyarios/data/sources/remote/contact_remote_source.dart' as _i3;
import 'package:nyarios/domain/model/contact.dart' as _i7;
import 'package:nyarios/domain/model/profile.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSharedLocalSource_0 extends _i1.SmartFake
    implements _i2.SharedLocalSource {
  _FakeSharedLocalSource_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeContactRemoteSource_1 extends _i1.SmartFake
    implements _i3.ContactRemoteSource {
  _FakeContactRemoteSource_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ContactRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockContactRepository extends _i1.Mock implements _i4.ContactRepository {
  MockContactRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SharedLocalSource get localSource =>
      (super.noSuchMethod(
            Invocation.getter(#localSource),
            returnValue: _FakeSharedLocalSource_0(
              this,
              Invocation.getter(#localSource),
            ),
          )
          as _i2.SharedLocalSource);

  @override
  _i3.ContactRemoteSource get remoteSource =>
      (super.noSuchMethod(
            Invocation.getter(#remoteSource),
            returnValue: _FakeContactRemoteSource_1(
              this,
              Invocation.getter(#remoteSource),
            ),
          )
          as _i3.ContactRemoteSource);

  @override
  _i5.Future<List<_i6.Profile>> loadContacts(String? status) =>
      (super.noSuchMethod(
            Invocation.method(#loadContacts, [status]),
            returnValue: _i5.Future<List<_i6.Profile>>.value(<_i6.Profile>[]),
          )
          as _i5.Future<List<_i6.Profile>>);

  @override
  _i5.Future<void> changeContactStatus(String? otherUserId, String? status) =>
      (super.noSuchMethod(
            Invocation.method(#changeContactStatus, [otherUserId, status]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i7.Contact?> loadSingleContact(String? profileId) =>
      (super.noSuchMethod(
            Invocation.method(#loadSingleContact, [profileId]),
            returnValue: _i5.Future<_i7.Contact?>.value(),
          )
          as _i5.Future<_i7.Contact?>);
}
